### ISSUE TITLE
!!! Exception during processing !!! Failed to import transformers.integrations.bitsandbytes because of the following error (look up to see its traceback):

### ISSUE THREAD

**Issue by haisheng666** [IuvenisSapiens/ComfyUI_MiniCPM-V-2_6-int4#11]
There are many problems with the project at the beginning! Please solve them for me.

!!! Exception during processing !!! Failed to import transformers.integrations.bitsandbytes because of the following error (look up to see its traceback):

        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
Traceback (most recent call last):
  File "D:\miniconda3\envs\comfyui_huishi\Lib\site-packages\transformers\utils\import_utils.py", line 1567, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda3\envs\comfyui_huishi\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\miniconda3\envs\comfyui_huishi\Lib\site-packages\transformers\integrations\bitsandbytes.py", line 13, in <module>
    import bitsandbytes as bnb
  File "D:\miniconda3\envs\comfyui_huishi\Lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "D:\miniconda3\envs\comfyui_huishi\Lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "D:\miniconda3\envs\comfyui_huishi\Lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>

**Comment by IuvenisSapiens** [comment]
Upgrade your bitsandbytes package to version 0.43.3 by running the command 

```powershell
pip install bitsandbytes>=0.43.3
```
