### ISSUE TITLE
ModuleNotFoundError: No module named 'transformers.models.qwen2'

### ISSUE THREAD

**Issue by lcWu-master** [IuvenisSapiens/ComfyUI_MiniCPM-V-2_6-int4#14]

**Comment by lcWu-master** [comment]
File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\cache\huggingface\modules\transformers_modules\local\tokenization_minicpmv_fast.py", line 1, in <module>
    from transformers.models.qwen2 import Qwen2TokenizerFast
ModuleNotFoundError: No module named 'transformers.models.qwen2'

Prompt executed in 0.06 seconds
got prompt
!!! Exception during processing !!! 'NoneType' object has no attribute 'eval'
Traceback (most recent call last):
  File "C:\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 316, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 191, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 168, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 157, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MiniCPM-V\nodes.py", line 58, in inference
    self.model.eval()
    ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'eval'

Prompt executed in 0.01 seconds

**Comment by IuvenisSapiens** [comment]
You should update the custom node, `ComfyUI_MiniCPM-V-2_6-int4`, to its latest version to ensure compatibility with the system and to address any known issues.

**Comment by lcWu-master** [comment]
thanks ,is fine
